name: Create release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Zip Folder
        run: zip -r release.zip .
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
        